// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA__5XkL0GuTJiTWNT2jQ_Y5GGO-eBx3aY',
    appId: '1:248151386902:web:2e5b902a7c7e8b0cfbbe37',
    messagingSenderId: '248151386902',
    projectId: 'irrigationsys-f31ac',
    authDomain: 'irrigationsys-f31ac.firebaseapp.com',
    databaseURL: 'https://irrigationsys-f31ac-default-rtdb.firebaseio.com',
    storageBucket: 'irrigationsys-f31ac.appspot.com',
    measurementId: 'G-DM0ESNNGLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWX_4atc2qGXnrz5sJpxDy2kBc39fu19Y',
    appId: '1:248151386902:android:2306167f887afe8dfbbe37',
    messagingSenderId: '248151386902',
    projectId: 'irrigationsys-f31ac',
    databaseURL: 'https://irrigationsys-f31ac-default-rtdb.firebaseio.com',
    storageBucket: 'irrigationsys-f31ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxOoyrr5mbOfmccNCVMAnZ9rFCxAlzhzY',
    appId: '1:248151386902:ios:3751381f872fa8eafbbe37',
    messagingSenderId: '248151386902',
    projectId: 'irrigationsys-f31ac',
    databaseURL: 'https://irrigationsys-f31ac-default-rtdb.firebaseio.com',
    storageBucket: 'irrigationsys-f31ac.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxOoyrr5mbOfmccNCVMAnZ9rFCxAlzhzY',
    appId: '1:248151386902:ios:7b4604db11497336fbbe37',
    messagingSenderId: '248151386902',
    projectId: 'irrigationsys-f31ac',
    databaseURL: 'https://irrigationsys-f31ac-default-rtdb.firebaseio.com',
    storageBucket: 'irrigationsys-f31ac.appspot.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
